### ISSUE TITLE
Add option to not restart Valetudo

### ISSUE THREAD

**Issue by timoschwarzer** [pkoehlers/maploader#17]
Valetudo refreshes the map automatically at least every 60 seconds and map refreshing works fine for me without restarting Valetudo in the process. (Dreame W10)

**Comment by pkoehlers** [comment]
Actually never tried without restarting. But will definitely check it on my
end.

Were you planning to submit a PR e.g. for an env var controlling this?

Timo Schwarzer ***@***.***> schrieb am Do., 21. Sept. 2023,
18:07:

**Comment by timoschwarzer** [comment]
I can make one later! I wasn't sure if I missed something and restarting it is actually required for some non-obvious reason 😅

**Comment by pkoehlers** [comment]
Ok 😄 Only other reason for me to keep the Valetudo restart is that I use it in HomeAssistant to reliably tell, if a map change is completely done and segment cleaning can be started for the desired map

**Comment by timoschwarzer** [comment]
@pkoehlers I added a new `starting_services` status that is set as long as the `ava` process is not ready yet. So *in theory* you could watch for a state change from `starting_services` → `idle` and *should* be able to start cleaning afterwards :sweat_smile:

**Comment by AndreKR** [comment]
FWIW I did a cursory review and I am currently using this branch on my W10 and everything works as intended.

**Comment by pkoehlers** [comment]
> @pkoehlers I added a new `starting_services` status that is set as long as the `ava` process is not ready yet. So _in theory_ you could watch for a state change from `starting_services` → `idle` and _should_ be able to start cleaning afterwards 😅
> 
> I didn't try automating it but I waited for it to be idle again and immediately started a zone cleaning, that worked.

Thanks for the PR! 

By the way, it does not directly accept a cleaning request, after state switches to idle. But this is still a bit faster than the Valetudo restart 👍
