### ISSUE TITLE
Where to amend environment variable?

### ISSUE THREAD

**Issue by j-inc** [pkoehlers/maploader#41]
Apologies if this is a stupid question, but where should environment variables be set? Documents do not specify.

I am looking to add `WAV_FILE_MAP_LOADED=/data/maploader/wav/map_change_{map_name}.wav` but am unclear in what file it should be placed and with what syntax.

I'm using a Dreame L10s Ultra running Valetudo and maploader. MQTT reports indicate maploader is functioning properly.

**Comment by pkoehlers** [comment]
Hi, if you followed the readme you should have added `VALETUDO_CONFIG_PATH=/data/valetudo_config.json /data/maploader-binary > /dev/null 2>&1 &` to the file `/data/_root_postboot.sh`.

You can just add other environment variables by writing them space separated in front of this command: `WAV_FILE_MAP_LOADED=/data/... VALETUDO_CONFIG_PATH=/data/valetudo_config.json /data/maploader-binary > /dev/null 2>&1 &`

**Comment by j-inc** [comment]
Thanks, I had done that, and assumed the variables should've been added in the postboot script but was just unclear as to where, syntax-wise. I appreciate the clarification!
